name: flutter_slidable
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
version: 0.5.7
homepage: https://github.com/letsar/flutter_slidable

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

environment:
  sdk: ">=2.8.0 <3.0.0"
